[package]
name = "sistema-solar-rust"
version = "0.1.0"
authors = ["Adriano Souza Barbieri <adriano2147@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "*"
gl = "*"
glm = "*"
tobj = "*"
num = "*"